# Basic options
title: Intermediate Version Control
short_name: intermediate-vc
developers: [Stephen Cook]
description: Version control for intermediate workflows and collaboration.
n_sessions: 2
prereq: Introduction to Version Control
url: https://coding-for-reproducible-research.github.io/intermediate-version-control

# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:path/index.html
    sort_by: lesson

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page

# Build settings
theme: jekyll-theme-slate
